# Generated by Django 4.2.5 on 2023-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student name')),
                ('father_name', models.CharField(max_length=100, verbose_name='father name')),
                ('mother_name', models.CharField(max_length=100, verbose_name='mother name')),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=15, verbose_name='contact no')),
                ('date', models.DateField(verbose_name='date of admission')),
                ('class_name', models.CharField(max_length=50, verbose_name='class')),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=100, verbose_name='parent email')),
                ('roll_number', models.CharField(max_length=20, unique=True, verbose_name='roll number')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
